server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
            - Path=/posts/**

        - id: FEED-SERVICE
          uri: lb://FEED-SERVICE
          predicates:
            - Path=/feed/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}